### ISSUE TITLE
Option to remove horizontal line at the top?

### ISSUE THREAD

**Issue by ladytintagel** [NayamAmarshe/please#10]
Hello there, I love the app, it's already replaced Neofetch on my production machine.
However, I use a tiling WM, and that means that often, my terminal windows are resized after opening, if I open additional windows in that workspace.  This breaks the task list, because the horizontal line at the top forces all text below to wrap when the terminal window shrinks horizontally.
It's not a huge deal, I have aliased 'clrpls' to clear the terminal and relaunch 'please', but it would be nice to be able to eliminate that top line so that resizing the terminal window is more forgiving.
Thank you for making such a great tool :)

**Comment by NayamAmarshe** [comment]
[Commit 70](https://github.com/NayamAmarshe/please/commit/f0ad1795c8cba5030d7285a193c044133d77b6ab) adds an option to disable the horizontal line by adding `"disable_line": true` at the end of please's config.json :)

**Comment by NayamAmarshe** [comment]
v0.2 is out!
https://github.com/NayamAmarshe/please#remove-horizontal-line-in-pleases-output
