### ISSUE TITLE
Unknown character on windows

### ISSUE THREAD

**Issue by MalikAza** [NayamAmarshe/please#12]
Running on windows with python3.9.6 64-bit:

Seems like the emoticones are not recognized. ([screenshot example](https://i.imgur.com/pp00FOW.png))

**Comment by NayamAmarshe** [comment]
Are you using the windows terminal or cmd?

**Comment by CodePleaseRun** [comment]
the tick & cross in the program is `U+2705`, and `U+274C` respectively in Unicode.
Most probably your terminal is using fonts that don't have anything mapped to `U+2705` and `U+274C`.

You can use the Character Map that comes with Windows to check different Unicode characters mapped to each individual font

**Comment by MalikAza** [comment]
> Are you using the windows terminal or cmd?

I'm using cmd on the screenshot, but just tested it on Windows PowerShell and got the same thing.


> the tick & cross in the program is `U+2705`, and `U+274C` respectively in Unicode. Most probably your terminal is using fonts that don't have anything mapped to `U+2705` and `U+274C`.
> 
> You can use the Character Map that comes with Windows to check different Unicode characters mapped to each individual font

Just checked out the font style and the Character Map. I've never changed the cmd font style, seems like the default one is `Consolas` and ... yup nothing mapped to `U+2705` and `U+274C`. Thanks for the advice!

**Comment by NayamAmarshe** [comment]
> > Are you using the windows terminal or cmd?
> 
> I'm using cmd on the screenshot, but just tested it on Windows PowerShell and got the same thing.
> 
> > the tick & cross in the program is `U+2705`, and `U+274C` respectively in Unicode. Most probably your terminal is using fonts that don't have anything mapped to `U+2705` and `U+274C`.
> > You can use the Character Map that comes with Windows to check different Unicode characters mapped to each individual font
> 
> Just checked out the font style and the Character Map. I've never changed the cmd font style, seems like the default one is `Consolas` and ... yup nothing mapped to `U+2705` and `U+274C`. Thanks for the advice!

Currently, we do not explicitly support Windows CMD and Powershell even though Python makes them cross-platform.
I suggest changing your font or your terminal, Fluent or Windows terminals are better for these things.
