### ISSUE TITLE
New feature: auth method and syncronism to different equipments

### ISSUE THREAD

**Issue by andre-almeid** [NayamAmarshe/please#16]
Hi...
One featurethat I'm interested in is synchronization with different equipments. I have three desktops and laptops and I find an account and task sync to be a nice feature.
I can help with that too. Let me know if you need some help.

Good work guys.

**Comment by NayamAmarshe** [comment]
The current scope of please does not allow for such complexity as it would only increase code size and the startup time.
A good idea for synchronization is to use symlinks for the config.json stored in ~/.config/please.
Another idea is to use a GitHub repository to sync the config.json file easily.

I know these are not ideal and you would like please to have an inbuilt support for sync, but the main aim for please is to be simple. The real problem with adding new features is the increased startup time, which we cannot compromise with at any cost.
