### ISSUE TITLE
[Suggestion] Clean Done and Create History file

### ISSUE THREAD

**Issue by mozram** [NayamAmarshe/please#17]
First, thank you for this awesome simple, yet very useful program.

To further improve usability of this program, I  want to propose 2  new features:

1. Batch remove done task. It can become a chore to remove done task 1-by-1. Perhaps an API such as `please clean`.
2. Any deleted should be moved to another file such as `history.json`. Then, introduce new API such as `please history` to display all done and "cleaned" task. This should allow the user to keep task history, while keeping the main task clean from bloat.

I understand the main concern is speed. Both of above suggestion should not impact the performance as it was outside of default `please` command.

**Comment by TGS963** [comment]
Hey! Thank you for the suggestion! I have added the a "clean" command in the latest commit, just as you suggested.

I am not very sure about the history feature though, We will think about what we should do with that.

**Comment by mozram** [comment]
Thanks! History stuff is more like good to have, not essential. But clean, that's a huge QoL improvement!

**Comment by NayamAmarshe** [comment]
This feature will be in v0.2

**Comment by NayamAmarshe** [comment]
v0.2 is out :)
