### ISSUE TITLE
Support for todo.txt

### ISSUE THREAD

**Issue by mdbdb** [NayamAmarshe/please#19]
Is it possible to read an existing todo.txt file at startup? All todos of the day or the week should then be displayed.

A synchronization is not necessary, for this there would be other tools, such as syncthing.

**Comment by TGS963** [comment]
Hmm, do you mean something like having a list of tasks that you want to add at once using a text file? Cuz it reads the config file at startup and that contains all tasks

**Comment by mdbdb** [comment]
Sorry, I should have worded it more precisely.

I mean support for the format todo.txt as described here: https://github.com/todotxt/todo.txt or http://todotxt.org/

**Comment by mdbdb** [comment]
Exactly. If please could use the existing todo.txt file and show the tasks of the current day or week, that would be great.

**Comment by TGS963** [comment]
We will definitely keep this feature request in mind. I was thinking that we could add a command to sync the please config with the todo.txt file. Should be added in the next commit 👍
