### ISSUE TITLE
Is there a way to change the time format of please, to 24 hours instead of 12?

### ISSUE THREAD

**Issue by AgentCasey** [NayamAmarshe/please#20]
I prefer seeing my time in the 24 hour format I've customized my time and date format in the .bashrc script however, please displays time in the 12 hour AM, PM style. I suspect the answer may be located in please.py but I'm not sure how to go about customizing the settings.  I know it's not really an issue, but if anyone knows how I could do what I want, I'd be very happy and grateful. Thanks.

**Comment by AgentCasey** [comment]
Never mind, I think I may have found a temporary fix for displaying 24 hour time format. On line 196:83 of ~/.local/lib/python3.X.X/site-packages/please/please.py, I've made a backup copy of please.py and edited the file and I've changed %I to %H I'll find out if I'm correct in under four minutes.

**Comment by NayamAmarshe** [comment]
#9 

Gonna work on releasing the new update in the next few days.

**Comment by AgentCasey** [comment]
Thank you NayamAmarshe, I appreciate that and thanks for the creative software.

**Comment by NayamAmarshe** [comment]
v0.2 is out :)
