### ISSUE TITLE
Possibility to disable the motivational quotes and `Hello Name!  It's`?

### ISSUE THREAD

**Issue by lamyergeier** [NayamAmarshe/please#22]
In the spirit of minimalism, please privide option to disable the motivational quotes and `Hello Name!  It's`? Also, option to hide `Task` Table header.

**Comment by NayamAmarshe** [comment]
I believe that would defeat the purpose of please. While greeting is an important part of it, the more important part is the tasks table that's supposed to be 'in your face' to remind you of the urgency. If you just want a simple greeting with date, I think it would be far easier to just use bash to manually print a greeting text like that.

If you would still like to use please and disable those, you can easily delete those lines from the show() function in `~/.local/lib/python3.X.X/site-packages/please/please.py` file. Let me know if you need any help with that :)

**Comment by lamyergeier** [comment]
My request Was not to hide the task table but the task header.

**Comment by NayamAmarshe** [comment]
> My request Was not to hide the task table but the table header.

Oh, like the Number, Name and the rest? Yes, we can consider it :) 

Meanwhile, you can disable it on your local installation. It's pretty simple, all you need to do is to add `show_header=False,` in showtasks() function, like this:
![image](https://user-images.githubusercontent.com/25067102/178164899-44c884b1-f0b2-4489-9526-b9073b7dd7b7.png)

In future, we'll consider adding some additional configuration options to modularize the output. in v0.2 you can disable the horizontal line, so we'll add some more for disabling each part individually. Thanks!
