### ISSUE TITLE
Please doesn't show "Hello ..., it's ...." 

### ISSUE THREAD

**Issue by radstevee** [NayamAmarshe/please#25]
I just installed it, and it just shows the quote and tasks, here's a screenshot
![2022-08-05-222220_1280x800_scrot](https://user-images.githubusercontent.com/96977790/183157298-46649d35-34ca-4403-8bf8-24730d183109.png)

**Comment by ChemDevv** [comment]
I have the same issue.

**Comment by ChemDevv** [comment]
@radstevee I fixed this issue locally. It looks like adding `"disable_line": true` to the end of my `~/.config/please/please.json` file causes please to include the greeting message. 

Oddly enough, including `"disable_line": false` does not fix the issue.

**Comment by NayamAmarshe** [comment]
> @radstevee I fixed this issue locally. It looks like adding `"disable_line": true` to the end of my `~/.config/please/config.json` file causes please to include the greeting message.
> 
> Oddly enough, including `"disable_line": false` does not fix the issue.
> 
> Here is what my config.json file looks like:
> 
> ```
> {
>   "user_name": "David",
>   "initial_setup_done": true,
>   "tasks": [
>     {
>       "name": "test",
>       "done": false
>     }
>   ],
>   "time_format_24h": true,
>   "disable_line": true
> }
> ```

It's possible that the issue is caused by your terminal not being able to render the horizontal line and hence not rendering the whole line itself. I'll add a note in the readme.

**Comment by ChemDevv** [comment]
> > @radstevee I fixed this issue locally. It looks like adding `"disable_line": true` to the end of my `~/.config/please/config.json` file causes please to include the greeting message.
> > Oddly enough, including `"disable_line": false` does not fix the issue.
> > Here is what my config.json file looks like:
> > ```
> > {
> >   "user_name": "David",
> >   "initial_setup_done": true,
> >   "tasks": [
> >     {
> >       "name": "test",
> >       "done": false
> >     }
> >   ],
> >   "time_format_24h": true,
> >   "disable_line": true
> > }
> > ```
> 
> It's possible that the issue is caused by your terminal not being able to render the horizontal line and hence not rendering the whole line itself. I'll add a note in the readme.

My terminal is able to render the horizontal line. Previously, it rendered the horizontal line like in the OP's first picture.
