### ISSUE TITLE
Improvement: Option to add task without string quotes `"`

### ISSUE THREAD

**Issue by rabilrbl** [NayamAmarshe/please#27]
Wouldn't it be better to not have `"` quotes attached when naming a task

All other arguments after `add` can be added to form the title

Some people like me are lazy to reach and hold shift key for `"`

Instead of this command
`please add "Task name"`
this would be a choice
`please add Task name`

or atleast can we make it optional with config file

**Comment by NayamAmarshe** [comment]
I don't think I can really control that, it's just how the Typer parsing works. If anybody's got any ideas, please feel free to let me know :)

**Comment by NayamAmarshe** [comment]
Yeah, checked again, definitely not possible. This is a python typer limitation, spaces are parsed as separation for arguments.
