### ISSUE TITLE
Not showing greetings

### ISSUE THREAD

**Issue by bartolek153** [NayamAmarshe/please#28]
The greetings are not being displayed. I attached a screenshot of how it looks, and my JSON config file as well.
![please_issue](https://user-images.githubusercontent.com/110190812/183706871-71a0416b-890e-4ddc-b7e8-184af426ad37.png)
![please_config](https://user-images.githubusercontent.com/110190812/183706907-932c122a-4847-4798-b3c6-0cf8811edde9.png)

I installed it via pip. Don't know if this might be related to the issues.

By the way, I really liked the idea. Thanks for this amazing CLI tool.

**Comment by bartolek153** [comment]
Oh, I'm sorry. I just realized what was wrong. It was missing `"disable_line": true` in my config file. I misconfused, but now it's working.

![please](https://user-images.githubusercontent.com/110190812/183708611-011eeb4c-eb69-45d2-b2e0-7d34205e4bbe.png)

**Comment by NayamAmarshe** [comment]
> Oh, I'm sorry. I just realized what was wrong. It was missing `"disable_line": true` in my config file. I misconfused, but now it's working.
> 
> ![please](https://user-images.githubusercontent.com/110190812/183708611-011eeb4c-eb69-45d2-b2e0-7d34205e4bbe.png)

It happens when the terminal is unable to render the horizontal line, glad you got it fixed :)
I should probably add a note about it.
