### ISSUE TITLE
TimeFormat behaves weird at startup

### ISSUE THREAD

**Issue by p-hash** [NayamAmarshe/please#33]
![image](https://user-images.githubusercontent.com/3995232/214509496-1bb4e610-cb40-4731-918c-786eed17535a.png)

It looks like default value makes time to appear in **12h** format, but for `changetimeformat` command (which does change 24h to 12h) the default value appears as **24h**

**Comment by NayamAmarshe** [comment]
Should hopefully be fixed :)
