### ISSUE TITLE
After installing please does not work, wrong file edited (.-bashrc).

### ISSUE THREAD

**Issue by ztjuh** [NayamAmarshe/please#4]
```
zkitzo@Hetzner:~$ please
-bash: please: command not found
zkitzo@Hetzner:~$ source .bashrc
zkitzo@Hetzner:~$ please
-bash: please: command not found
zkitzo@Hetzner:~$ nano .bashrc
zkitzo@Hetzner:~$ echo `echo $0`
-bash
zkitzo@Hetzner:~$ ls -lAh
-rw-rw-r--  1 zkitzo zkitzo  209 May 31 19:49 .bash_aliases
-rw-------  1 zkitzo zkitzo 205K Jun 13 17:11 .bash_history
-rw-r--r--  1 zkitzo zkitzo  220 Jan  7 22:16 .bash_logout
-rw-rw-r--  1 zkitzo zkitzo    7 Jun 13 17:10 .-bashrc
-rw-r--r--  1 zkitzo zkitzo 4.1K May 22 21:08 .bashrc
```

Also `/home/zkitzo/.local/bin` is not in my `$PATH`. Easy to add but I think you should fix it!

**Comment by NayamAmarshe** [comment]
> Also /home/zkitzo/.local/bin is not in my $PATH. Easy to add but I think you should fix it!

Yes, that must be the problem. Unfortunately, it's not something I can fix since it's distro and python dependent. The solution for 'command not found' is to add `~/.local/bin` to your **PATH**. I can add a warning for this in the readme, thanks for reporting!

**Comment by ztjuh** [comment]
Don't forget that `$0` === `-bash` on my Ubuntu system.

**Comment by NayamAmarshe** [comment]
> Don't forget that `$0` === `-bash` on my Ubuntu system.

I'll update the instructions to include manual editing :)
