### ISSUE TITLE
"please daily" - > Error: No such command 'daily'

### ISSUE THREAD

**Issue by bleo181-dev** [NayamAmarshe/please#46]
I am on linux with the latest version of "please" at the time of writing. When I run the `please daily` command to start the program once a day, as described in the README, I get this error:
```
Usage: please [OPTIONS] COMMAND [ARGS]...
Try 'please --help' for help.

Error: No such command 'daily'.
```

**Comment by NayamAmarshe** [comment]
Oh right, sorry. It's actually not in the latest version. The feature and readme update was added after release 😅

**Comment by sophisticatedDreamer** [comment]
Same error message here. Does your answer mean `please daily` was removed? Or does it mean `please daily` will be published in a next release?

Thanks for this nice tool, btw!

**Comment by NayamAmarshe** [comment]
It'll be in the next release :)
