### ISSUE TITLE
No status images since last update

### ISSUE THREAD

**Issue by DolevRavid** [NayamAmarshe/please#47]
Hi! 
I felt in love with this amazing tool
and I'm working with it as my primary To-Do list app. 
One issue I can't ignore is since the last update I can't see the status icons.
I'm running Manjaro with Gnome. 

Maybe you can assist me? 

![צילום מסך מ־2023-04-03 14-02-40](https://user-images.githubusercontent.com/38867495/229492578-077ea57d-f6a5-479e-bd15-3f8365b34f49.png)

**Comment by NayamAmarshe** [comment]
That's pretty strange.
Try this: `sudo pacman -S gnome-terminal noto-fonts-emoji`

**Comment by DolevRavid** [comment]
Problem solved :)

thanks for the help!  :1st_place_medal:
