### ISSUE TITLE
Possibility to change tasks order

### ISSUE THREAD

**Issue by andre-almeid** [NayamAmarshe/please#8]
One interesting feature is the possibility to change the order of the tasks. This is a nice and simple feature you can implement and is important for the flow of tasks.

**Comment by NayamAmarshe** [comment]
Could be an interesting feature. Will think about it, the focus of this project is on ease of use and simplicity mostly, so will have to think about the ways I can integrate this feature :)

**Comment by TGS963** [comment]
The most recent commit adds the feature you had suggested. So, I will be closing the issue now. Thanks for the suggestion :)

**Comment by NayamAmarshe** [comment]
v0.2 is out with this feature :)
